apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountmanagement
  namespace: "proj-gr4"
  labels:
    app: accountmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountmanagement
  template:
    metadata:
      labels:
        app: accountmanagement
    spec:
      containers:
      - name: accountmanagement
        image: mortenlyngosenquist/accountmanagement:latest
---
apiVersion: v1
kind: Service
metadata: 
  name: accountmanagement
  namespace: "proj-gr4"
spec:
  selector:
    app: accountmanagement
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer
    
      
      
