apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountmanagement
  namespace: "proj-gr4"
  labels:
    app: accountmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountmanagement
  template:
    metadata:
      labels:
        app: accountmanagement
    spec:
      containers:
      - name: accountmanagement
        image: mortenlyngosenquist/accountmanagement:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata: 
  name: accountmanagement
  namespace: "proj-gr4"
  labels:
    app: accountmanagement
spec:
  selector:
    app: accountmanagement
  ports:
    - port: 8080
      targetPort: 80

    
      
      
