apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proj-gr4
  name: mssqlserver
  labels:
    app: mssqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssqlserver
  template:
    metadata:
      labels:
        app: mssqlserver
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssqlserver
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "F20ItOnk123" 
        - name: MSSQL_DATA_DIR
          value: /var/opt/mssql/mdf
        - name: MSSQL_LOG_DIR
          value: /var/opt/mssql/ldf 
        resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
              
        volumeMounts:
        - name: accountmanagement-base-volume
          mountPath: /var/opt/mssql
        - name: accountmanagement-ldf-volume
          mountPath: /var/opt/mssql/ldf
        - name: accountmanagement-mdf-volume
          mountPath: /var/opt/mssql/mdf
      volumes:
      - name: accountmanagement-base-volume
        persistentVolumeClaim:
          claimName: accountmanagement-base-volume
      - name: accountmanagement-mdf-volume
        persistentVolumeClaim:
          claimName: accountmanagement-mdf-volume
      - name: accountmanagement-ldf-volume
        persistentVolumeClaim:
          claimName: accountmanagement-ldf-volume		  
---
apiVersion: v1
kind: Service
metadata:
  namespace: proj-gr4
  name: mssqlserver
  labels:
    app: mssqlserver
spec:
  selector:
    app: mssqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433