kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: proj-gr4
  name: accountmanagement-base-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: proj-gr4
  name: accountmanagement-mdf-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
--- 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: proj-gr4
  name: accountmanagement-ldf-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi	  